Repository hakzzang/SnacKB, pull requests merged in 2019-06, with the labels that each got.

#3 closed #2 Update Camera and Permission Manager.
  .idea/misc.xml
  app/src/main/java/hbs/com/snackb/ui/MainActivity.kt
  app/src/main/java/hbs/com/snackb/utils/CameraManager.kt
  app/src/main/java/hbs/com/snackb/utils/PermissionManager.kt
Labels: 간단해요, 확인해줬으면 좋겠어요

#6 closed #5 Make an AR Character function.
  app/build.gradle
  app/model/model.sfb
  app/src/main/AndroidManifest.xml
  app/src/main/assets/model.sfb
  app/src/main/java/hbs/com/snackb/model/materials.mtl
  app/src/main/java/hbs/com/snackb/model/model.obj
  app/src/main/java/hbs/com/snackb/model/model.sfa
  app/src/main/java/hbs/com/snackb/ui/MainActivity.kt
  app/src/main/java/hbs/com/snackb/utils/ARCoreManager.kt
  app/src/main/res/layout/activity_main.xml
  build.gradle
Labels: 복잡해요

#8 closed #7 Make a SceneformManager.
  app/src/main/java/hbs/com/snackb/ui/MainActivity.kt
  app/src/main/java/hbs/com/snackb/utils/CameraManager.kt
  app/src/main/java/hbs/com/snackb/utils/SceneformManager.kt
  app/src/main/res/layout/activity_main.xml
Labels: 간단해요, 새우버거가 함께해요

#11 closed #9 Cloud 환경을 제공하는 AR Core 기능 추가
  app/build.gradle
  app/model/model.sfb
  app/src/main/AndroidManifest.xml
  app/src/main/assets/model.sfb
  app/src/main/java/hbs/com/snackb/model/materials.mtl
  app/src/main/java/hbs/com/snackb/model/model.obj
  app/src/main/java/hbs/com/snackb/model/model.sfa
  app/src/main/java/hbs/com/snackb/ui/CloudAnchorFragment.kt
  app/src/main/java/hbs/com/snackb/ui/MainActivity.kt
  app/src/main/java/hbs/com/snackb/utils/AppAnchorState.kt
  app/src/main/java/hbs/com/snackb/utils/SceneformManager.kt
  app/src/main/java/hbs/com/snackb/utils/SnackbarHelper.kt
  app/src/main/java/hbs/com/snackb/utils/StoreManager.kt
  app/src/main/res/drawable/bg_radius_account_info.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/view_ar_account_info.xml
  build.gradle
Labels: 복잡해요, 새우버거가 함께해요

#13 closed #12 Naver Map 연동하기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/snackb/ui/MapActivity.kt
  app/src/main/java/hbs/com/snackb/viewmodel/MapViewModel.kt
  app/src/main/res/layout/activity_map.xml
  build.gradle
Labels: 간단해요, 새우버거가 함께해요

#15 closed #14 메인페이지 UI 작성
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/snackb/ui/CustomARActivity.kt
  app/src/main/java/hbs/com/snackb/ui/MapActivity.kt
  app/src/main/res/font/nanumgothic_bold.ttf
  app/src/main/res/font/nanumgothic_extrabold.ttf
  app/src/main/res/font/nanumgothic_regular.ttf
  app/src/main/res/layout/activity_ar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 간단해요

#17 closed #16 MainActivity 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/snackb/ui/main/FindingCategoryAdapter.kt
  app/src/main/java/hbs/com/snackb/ui/main/MainActivity.kt
  app/src/main/java/hbs/com/snackb/utils/FindingCategory.kt
  app/src/main/java/hbs/com/snackb/utils/StartSnapHelper.java
  app/src/main/java/hbs/com/snackb/viewmodel/MainViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_around_bank.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 복잡해요

#19 closed #18 KB API인터페이스화
  app/build.gradle
  app/src/main/java/hbs/com/snackb/api/BaseAPI.kt
  app/src/main/java/hbs/com/snackb/api/KBApi.kt
  app/src/main/java/hbs/com/snackb/api/NetModule.kt
  app/src/main/java/hbs/com/snackb/repository/KBRepository.kt
  app/src/main/java/hbs/com/snackb/ui/main/MainActivity.kt
  app/src/main/java/hbs/com/snackb/utils/Base64Utils.java
  app/src/main/java/hbs/com/snackb/utils/HMACUtils.kt
  app/src/main/java/hbs/com/snackb/utils/JJwtHelper.kt
Labels: 복잡해요, 확인해줬으면 좋겠어요

#23 closed #22 Defender 모듈 작업 추가
  .idea/gradle.xml
  .idea/modules.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
  defender/.gitignore
  defender/build.gradle
  defender/proguard-rules.pro
  defender/src/androidTest/java/hbs/com/defender/ExampleInstrumentedTest.java
  defender/src/main/AndroidManifest.xml
  defender/src/main/assets/not_found.json
  defender/src/main/java/hbs/com/defender/ui/error/ErrorActivity.kt
  defender/src/main/java/hbs/com/defender/ui/error/HBSErrorApplication.kt
  defender/src/main/java/hbs/com/defender/ui/error/HBSExceptionHandler.kt
  defender/src/main/java/hbs/com/defender/ui/error/SimpleActivityLifecycleCallbacks.kt
  defender/src/main/res/layout/activity_error.xml
  defender/src/main/res/values/strings.xml
  defender/src/test/java/hbs/com/defender/ExampleUnitTest.java
  settings.gradle
Labels: 복잡해요, 새우버거가 함께해요

#27 closed #25 ERROR ACTIVITY UI 변경
  app/src/main/res/values-normal/dimens.xml
  defender/src/main/res/drawable/btn_rounded_purple.xml
  defender/src/main/res/drawable/btn_rounded_white.xml
  defender/src/main/res/font/nanumgothic_bold.ttf
  defender/src/main/res/font/nanumgothic_extrabold.ttf
  defender/src/main/res/font/nanumgothic_regular.ttf
  defender/src/main/res/layout/activity_error.xml
  defender/src/main/res/values/colors.xml
Labels: UI, 새우버거가 함께해요

#29 closed #28 UPDATE Defender UI
  defender/build.gradle
  defender/src/main/AndroidManifest.xml
  defender/src/main/assets/completed.json
  defender/src/main/assets/wizard_one.json
  defender/src/main/assets/wizard_three.json
  defender/src/main/assets/wizard_two.json
  defender/src/main/java/hbs/com/defender/ui/error/ErrorActivity.kt
  defender/src/main/java/hbs/com/defender/ui/report/ReportActivity.kt
  defender/src/main/java/hbs/com/defender/ui/report/ReportFragmentOne.kt
  defender/src/main/java/hbs/com/defender/ui/report/ReportFragmentThree.kt
  defender/src/main/java/hbs/com/defender/ui/report/ReportFragmentTwo.kt
  defender/src/main/java/hbs/com/defender/ui/report/ReportViewModel.kt
  defender/src/main/res/drawable/btn_rounded_grey.xml
  defender/src/main/res/layout/activity_error.xml
  defender/src/main/res/layout/activity_report.xml
  defender/src/main/res/layout/fragment_report_one.xml
  defender/src/main/res/layout/fragment_report_three.xml
  defender/src/main/res/layout/fragment_report_two.xml
  defender/src/main/res/values/strings.xml
Labels: UI, 복잡해요, 새우버거가 함께해요

#31 closed #30 네트워크 버그로 인한 현상 개선 중
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/snackb/api/BaseAPI.kt
  app/src/main/java/hbs/com/snackb/api/KBApi.kt
  app/src/main/java/hbs/com/snackb/api/NetModule.kt
  app/src/main/java/hbs/com/snackb/repository/KBRepository.kt
  app/src/main/java/hbs/com/snackb/ui/main/MainActivity.kt
  app/src/main/java/hbs/com/snackb/utils/JJwtHelper.kt
  app/src/main/java/hbs/com/snackb/utils/SecretUtils.java
  app/src/main/java/hbs/com/snackb/utils/Sha256Util.java
  defender/build.gradle
  defender/src/main/res/xml/network_security_config.xml
Labels: 복잡해요, 새우버거가 함께해요

#34 clsoed #33 Bank Account 획득 로직 추가
  .idea/misc.xml
  app/src/main/java/hbs/com/snackb/api/KBApi.kt
  app/src/main/java/hbs/com/snackb/models/BankAccount.kt
  app/src/main/java/hbs/com/snackb/models/BankTransaction.kt
  app/src/main/java/hbs/com/snackb/repository/KBRepository.kt
  app/src/main/java/hbs/com/snackb/ui/main/MainActivity.kt
Labels: 간단해요, 새우버거가 함께해요

#36 closed #35 Main UI 구조 수정
  app/src/main/java/hbs/com/snackb/ui/main/MainActivity.kt
  app/src/main/java/hbs/com/snackb/ui/main/RequestFBAppList.kt
  app/src/main/res/drawable/bg_radius_account_info.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_my_account.xml
Labels: UI, 새우버거가 함께해요

#38 closed #37 Error Library 관련 Firebase 추가 및 클라우드 작업
  app/build.gradle
  defender/build.gradle
  defender/src/main/java/hbs/com/defender/ui/error/ErrorActivity.kt
  defender/src/main/java/hbs/com/defender/ui/error/HBSErrorContent.kt
  defender/src/main/java/hbs/com/defender/ui/error/HBSExceptionHandler.kt
  defender/src/main/java/hbs/com/defender/ui/report/ReportActivity.kt
  defender/src/main/java/hbs/com/defender/ui/report/ReportFragmentThree.kt
  defender/src/main/java/hbs/com/defender/ui/report/ReportFragmentTwo.kt
  defender/src/main/res/values/strings.xml
Labels: 새우버거가 함께해요

#40 closed #39 계좌 정보 조회 추가 및 UI 개발
  app/src/main/java/hbs/com/snackb/models/BankAccount.kt
  app/src/main/java/hbs/com/snackb/models/BankTransaction.kt
  app/src/main/java/hbs/com/snackb/ui/main/MainActivity.kt
  app/src/main/java/hbs/com/snackb/ui/main/MyAccountListAdapter.kt
  app/src/main/java/hbs/com/snackb/ui/main/RequestFBAccountList.kt
  app/src/main/java/hbs/com/snackb/ui/main/RequestFBAppList.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_my_account.xml
Labels: UI, 새우버거가 함께해요
